# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templatka.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetAmlitudaCzas = QtWidgets.QWidget(self.centralwidget)
        self.widgetAmlitudaCzas.setObjectName("widgetAmlitudaCzas")
        self.verticalLayout.addWidget(self.widgetAmlitudaCzas)
        self.widgetWybor = QtWidgets.QWidget(self.centralwidget)
        self.widgetWybor.setObjectName("widgetWybor")
        self.verticalLayout.addWidget(self.widgetWybor)
        self.widgetSpektogram = QtWidgets.QWidget(self.centralwidget)
        self.widgetSpektogram.setObjectName("widgetSpektogram")
        self.verticalLayout.addWidget(self.widgetSpektogram)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 22))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.overlap40 = QtWidgets.QMenu(self.menubar)
        self.overlap40.setObjectName("overlap40")
        self.menusegmenty = QtWidgets.QMenu(self.menubar)
        self.menusegmenty.setObjectName("menusegmenty")
        self.menuOkna = QtWidgets.QMenu(self.menubar)
        self.menuOkna.setObjectName("menuOkna")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionotw_rz = QtWidgets.QAction(MainWindow)
        self.actionotw_rz.setObjectName("actionotw_rz")
        self.overlap_10 = QtWidgets.QAction(MainWindow)
        self.overlap_10.setObjectName("overlap_10")
        self.overlap20 = QtWidgets.QAction(MainWindow)
        self.overlap20.setObjectName("overlap20")
        self.overlap30 = QtWidgets.QAction(MainWindow)
        self.overlap30.setObjectName("overlap30")
        self.action40 = QtWidgets.QAction(MainWindow)
        self.action40.setObjectName("action40")
        self.overlap50 = QtWidgets.QAction(MainWindow)
        self.overlap50.setObjectName("overlap50")
        self.segment_256 = QtWidgets.QAction(MainWindow)
        self.segment_256.setObjectName("segment_256")
        self.segment_512 = QtWidgets.QAction(MainWindow)
        self.segment_512.setObjectName("segment_512")
        self.segment_1024 = QtWidgets.QAction(MainWindow)
        self.segment_1024.setObjectName("segment_1024")
        self.actionboxcar = QtWidgets.QAction(MainWindow)
        self.actionboxcar.setObjectName("actionboxcar")
        self.actiontriang = QtWidgets.QAction(MainWindow)
        self.actiontriang.setObjectName("actiontriang")
        self.actionblackman = QtWidgets.QAction(MainWindow)
        self.actionblackman.setObjectName("actionblackman")
        self.actionhamming = QtWidgets.QAction(MainWindow)
        self.actionhamming.setObjectName("actionhamming")
        self.actionhann = QtWidgets.QAction(MainWindow)
        self.actionhann.setObjectName("actionhann")
        self.actionbartlett = QtWidgets.QAction(MainWindow)
        self.actionbartlett.setObjectName("actionbartlett")
        self.actionflattop = QtWidgets.QAction(MainWindow)
        self.actionflattop.setObjectName("actionflattop")
        self.actionparzen = QtWidgets.QAction(MainWindow)
        self.actionparzen.setObjectName("actionparzen")
        self.menuPlik.addAction(self.actionotw_rz)
        self.overlap40.addAction(self.overlap_10)
        self.overlap40.addAction(self.overlap20)
        self.overlap40.addAction(self.action40)
        self.overlap40.addAction(self.overlap50)
        self.menusegmenty.addAction(self.segment_256)
        self.menusegmenty.addAction(self.segment_512)
        self.menusegmenty.addAction(self.segment_1024)
        self.menuOkna.addAction(self.actionboxcar)
        self.menuOkna.addAction(self.actiontriang)
        self.menuOkna.addAction(self.actionblackman)
        self.menuOkna.addAction(self.actionhamming)
        self.menuOkna.addAction(self.actionhann)
        self.menuOkna.addAction(self.actionbartlett)
        self.menuOkna.addAction(self.actionflattop)
        self.menuOkna.addAction(self.actionparzen)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.overlap40.menuAction())
        self.menubar.addAction(self.menusegmenty.menuAction())
        self.menubar.addAction(self.menuOkna.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.overlap40.setTitle(_translate("MainWindow", "Overlap"))
        self.menusegmenty.setTitle(_translate("MainWindow", "Segmenty"))
        self.menuOkna.setTitle(_translate("MainWindow", "Okna"))
        self.actionotw_rz.setText(_translate("MainWindow", "otwórz"))
        self.overlap_10.setText(_translate("MainWindow", "10"))
        self.overlap20.setText(_translate("MainWindow", "20"))
        self.overlap30.setText(_translate("MainWindow", "30"))
        self.action40.setText(_translate("MainWindow", "40"))
        self.overlap50.setText(_translate("MainWindow", "50"))
        self.segment_256.setText(_translate("MainWindow", "256"))
        self.segment_512.setText(_translate("MainWindow", "512"))
        self.segment_1024.setText(_translate("MainWindow", "1024"))
        self.actionboxcar.setText(_translate("MainWindow", "boxcar"))
        self.actiontriang.setText(_translate("MainWindow", "triang"))
        self.actionblackman.setText(_translate("MainWindow", "blackman"))
        self.actionhamming.setText(_translate("MainWindow", "hamming"))
        self.actionhann.setText(_translate("MainWindow", "hann"))
        self.actionbartlett.setText(_translate("MainWindow", "bartlett"))
        self.actionflattop.setText(_translate("MainWindow", "flattop"))
        self.actionparzen.setText(_translate("MainWindow", "parzen"))

